<?php

namespace HealthAdvisorBundle\Repository;

/**
 * ArticleNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleNoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function calculMoyenne($id)
    {
        //$q=$this->getEntityManager()->createQuery()
    }
}
