<?php

namespace HealthAdvisorBundle\Repository;

/**
 * ReponseSondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseSondageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNbrReponses($id_sondage,$reponse)
    {
        $r = $this->getEntityManager()
            ->createQuery("SELECT r FROM HealthAdvisorBundle:ReponseSondage r
                      WHERE r.sondage = '$id_sondage' and r.reponse='$reponse'");
        return $r->getResult();
    }

    public function findNbrTotalSondage($id_sondage)
    {
        $r = $this->getEntityManager()
            ->createQuery("SELECT COUNT (r) FROM HealthAdvisorBundle:ReponseSondage r
                      WHERE r.sondage = '$id_sondage'");
        return $r->getResult();
    }


}
