health_advisor_homepage:
    path:     /
    defaults: { _controller: HealthAdvisorBundle:Default:index }

index_admin:
    path:     /admin
    defaults: { _controller: HealthAdvisorBundle:Admin_Template:index }
afficher_aliment:
    path:     /admin/afficherAliment
    defaults: { _controller: HealthAdvisorBundle:Aliment:afficherAliment }
ajouter_aliment:
    path:     /admin/ajoutAliment
    defaults: { _controller: HealthAdvisorBundle:Aliment:ajouterAliment }
modifier_aliment:
    path:     /admin/modifAliment
    defaults: { _controller: HealthAdvisorBundle:Aliment:modifierAliment }
supprimer_aliment:
    path:     /admin/suppAliment
    defaults: { _controller: HealthAdvisorBundle:Aliment:supprimerAliment }
rechercher_aliment:
    path:     /admin/rechercheAliment
    defaults: { _controller: HealthAdvisorBundle:Aliment:rechercheAliment }
afficher_outilBiennetre:
    path:     /outils
    defaults: { _controller: HealthAdvisorBundle:Biennetre:indexOutilBiennetre }
ajouter_infoSante:
    path:     /outils/ajouterInfoSanter
    defaults: { _controller: HealthAdvisorBundle:Biennetre:ajouterInfoSante }
afficher_infoSante:
    path:     /outils/afficherInfoSante
    defaults: { _controller: HealthAdvisorBundle:Biennetre:afficherInfoSante }
