health_advisor_homepage:
    path:     /
    defaults: { _controller: HealthAdvisorBundle:Default:index }

index_admin:
    path:     /admin
    defaults: { _controller: HealthAdvisorBundle:Admin_Template:index }
index_medecin:
    path:     /medecin
    defaults: { _controller: HealthAdvisorBundle:Medecin:index }
admin_users:
    path:     /admin/afficher_users
    defaults: { _controller: HealthAdvisorBundle:Admin_Template:afficher_Users }