health_advisor_homepage:
    path:     /
    defaults: { _controller: HealthAdvisorBundle:Default:index }

index_admin:
    path:     /admin
    defaults: { _controller: HealthAdvisorBundle:Admin_Template:index }
index_medecin:
    path:     /medecin
    defaults: { _controller: HealthAdvisorBundle:Medecin:index }
ajout_patient:
    path:     /patient/{}
    defaults: { _controller: HealthAdvisorBundle:Patient:new }
admin_users:
    path:     /admin/afficher_users
    defaults: { _controller: HealthAdvisorBundle:Admin_Template:afficher_Users }
admin_supprimer:
    path:     /admin/supprimer
    defaults: { _controller: HealthAdvisorBundle:Admin_Template:supprimer_User }
ajoutEvt:
    path:     /ajoutEvt
    defaults: { _controller: HealthAdvisorBundle:Evennement:ajoutEvenement }
listEvt:
    path:     /listEvt
    defaults: { _controller: HealthAdvisorBundle:Evennement:listEvt }
deleteEvt:
    path:     /deleteEvt/{id}
    defaults: { _controller: HealthAdvisorBundle:Evennement:deleteEvt }
modifEvt:
    path:     /modifEvt/{id}
    defaults: { _controller: HealthAdvisorBundle:Evennement:modifEvt }